### PR TITLE
docs: fix lost description texts

### LINKED ISSUE #794: Api docs parameter default extraction removes parts of the description
### Describe the bug

Found while reviewing https://github.com/faker-js/faker/pull/792#discussion_r844871900 and writing https://github.com/faker-js/faker/pull/793.

https://github.com/faker-js/faker/blob/81171c9f9f2e548f9a86eaae3683ead7e28dbd72/scripts/apidoc/signature.ts#L301-L305

The code removes the description after the parameter default section.

### Reproduction

https://github.com/faker-js/faker/blob/81171c9f9f2e548f9a86eaae3683ead7e28dbd72/src/time.ts#L13-L18

grafik

### Additional Info

Possible solutions:

1) Require the default to be the last segment
2) Fix the code to not erase the suffix
3) Intentionally ignore the parts after the defaults (not recommended)

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #794

Here a few examples of the changes:

<details>
<summary><strong>Old1 (Click to exand)</strong></summary>

grafik

</details>

<details>
<summary><strong>New1 (Click to exand)</strong></summary>

grafik

</details>

<details>

<summary><strong>Old2 (Click to exand)</strong></summary>

grafik

</details>

<details>
<summary><strong>New2 (Click to exand)</strong></summary>

grafik

</details>

<details>
<summary><strong>Old3 (Click to exand)</strong></summary>

grafik

</details>

<details>
<summary><strong>New3 (Click to exand)</strong></summary>

grafik

</details>

I'm not sure about the CSS changes. IIRC we discussed at some point to not use it, but I don't remember why anymore.
If we don't display it as list items, then we have to remove the padding from the list though.

### CODE REVIEW

**Review by ejcheng — DISMISSED** [review]

**Review by pkuczynski — DISMISSED** [review]

File: scripts/apidoc/signature.ts [hunk 1]
```diff
@@ -60,7 +61,7 @@ function mdToHtml(md: string): string {
     console.debug('Rejected unsafe md:', md);
     console.error('Rejected unsafe html:', rawHtml.replace(/&gt;/g, '>'));
     console.error('Expected safe html:', safeHtml.replace(/&gt;/g, '>'));
-    throw new Error('Found unsafe html');
+    throw new FakerError('Found unsafe html');
```
Comment (Shinigami92) [inline scripts/apidoc/signature.ts:64]: This is a script, not faker source code, so should we **not** use `FakerError` here?

File: scripts/apidoc/signature.ts [hunk 2]
```diff
@@ -16,6 +16,7 @@ import type {
 } from '../../docs/.vitepress/components/api-docs/method';
 import vitepressConfig from '../../docs/.vitepress/config';
 import { faker } from '../../src';
+import { FakerError } from '../../src/errors/faker-error';
```
Comment (Shinigami92) [inline scripts/apidoc/signature.ts:19]: Please use FakerError only in `src/` (or `test/`) but not in `scripts/`

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]
