### PR TITLE
feat: lorem null response fix

### LINKED ISSUE #1131: `faker.lorem.word` can return `undefined` despite being typed as `string`
### Describe the bug

When calling `faker.lorem.word` with a length that doesn't have any matching words, it will return `undefined` while TypeScript thinks it's a `string`.

### Reproduction

```ts
const nonexistentWord = faker.lorem.word(9999) // <-- typed as `string`
console.log(nonexistentWord) // <-- will output `undefined`
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #1131

- Extended and exported the filterWordListByLength to add support for length ranges and fallback strategies
- Use the improved filterWordListByLength function for all `word.*` and `lorem.word` methods

### CODE REVIEW

File: src/modules/lorem/index.ts [hunk 1]
```diff
@@ -17,24 +18,38 @@ export class LoremModule {
...
+    options:
+      | number
+      | {
+          length?: number | { min: number; max: number };
+          strategy?: 'fail' | 'closest' | 'shortest' | 'longest' | 'any-length';
+        } = {}
+  ): string {
+    return this.faker.helpers.arrayElement(
+      filterWordListByLength({
+        ...(typeof options === 'number' ? { length: options } : options),
```
Comment (Shinigami92) [inline src/modules/lorem/index.ts:49]: Please extract this to its own line

File: src/modules/word/filterWordListByLength.ts [hunk 2]
```diff
@@ -0,0 +1,100 @@
+import { FakerError } from '../../errors/faker-error';
+
+/**
+ * The error handling strategies for the `filterWordListByLength` function.
+ *
+ * Always returns a new array.
+ */
+const strategies = {
```
Comment (Shinigami92) [inline src/modules/word/filterWordListByLength.ts:8]: This is a _root_-level `const`, so we might want to use UPPER casing

File: src/modules/word/filterWordListByLength.ts [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+  fail: () => {
+    throw new FakerError('No words found that match the given length.');
+  },
+  closest: (
+    wordList: string[],
+    length: { min: number; max: number }
+  ): string[] => {
+    const wordsByLength = wordList.reduce((data, word) => {
+      data[word.length] = data[word.length] || [];
```
Comment (Shinigami92) [inline src/modules/word/filterWordListByLength.ts:17]:
```suggestion
      data[word.length] ??= [];
```

File: src/modules/word/filterWordListByLength.ts [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+      data[word.length].push(word);
+      return data;
+    }, {} as Record<number, string[]>);
+
+    const min = Math.min(...Object.keys(wordsByLength).map(Number));
+    const max = Math.max(...Object.keys(wordsByLength).map(Number));
```
Comment (Shinigami92) [inline src/modules/word/filterWordListByLength.ts:23]:
```suggestion
    const variableName = Object.keys(wordsByLength).map(Number);
    const min = Math.min(...variableName);
    const max = Math.max(...variableName);
```

File: src/modules/word/filterWordListByLength.ts [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+    return wordList.filter(
+      (word) =>
+        word.length === length.min - closestOffset ||
+        word.length === length.max + closestOffset
+    );
+  },
+  shortest: (wordList: string[]): string[] => {
+    return wordList.filter(
+      (word) => word.length === Math.min(...wordList.map((word) => word.length))
```
Comment (Shinigami92) [inline src/modules/word/filterWordListByLength.ts:35]: You shadow the outer `word` variable in the inner `map`, please use different variable names for these two

Also applies for line 40

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

File: src/modules/word/filterWordListByLength.ts [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+
+    return wordList.filter(
+      (word) =>
+        word.length === length.min - closestOffset ||
+        word.length === length.max + closestOffset
+    );
+  },
+  shortest: (wordList: string[]): string[] => {
+    return wordList.filter(
+      (word) => word.length === Math.min(...wordList.map((w) => w.length))
```
Comment (Shinigami92) [inline src/modules/word/filterWordListByLength.ts:35]: I think you can extract `Math.min(...wordList.map((w) => w.length)` to its own line, that way it will only iterated once

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

File: src/modules/lorem/index.ts [hunk 7]
```diff
@@ -17,24 +18,39 @@ export class LoremModule {
...
+          strategy?: 'fail' | 'closest' | 'shortest' | 'longest' | 'any-length';
+        } = {}
+  ): string {
+    const opts = typeof options === 'number' ? { length: options } : options;
+    return this.faker.helpers.arrayElement(
+      filterWordListByLength({
+        ...opts,
+        wordList: this.faker.definitions.lorem.words,
+      })
+    );
```
Comment (ST-DDT) [inline src/modules/lorem/index.ts:53]: I thought about providing this as a standalone function in `faker.helpers`, but I'm not sure how to name it.

````ts
tobedefined(
    worldList: string[],
    options:
      | number
      | {
          length?: number | { min: number; max: number };
          strategy?: 'fail' | 'closest' | 'shortest' | 'longest' | 'any-length';
        } = {}
  ): string
````

`textArrayElement`?

File: src/modules/lorem/index.ts [hunk 8]
```diff
@@ -17,24 +18,39 @@ export class LoremModule {
...
    * Generates a word of a specified length.
    *
-   * @param length length of the word that should be returned. Defaults to a random length.
+   * Available error handling strategies:
+   *
+   * - `fail`: Throws an error if no words with the given length are found.
+   * - `shortest`: Returns any of the shortest words.
+   * - `closest`: Returns any of the words closest to the given length.
+   * - `longest`: Returns any of the longest words.
+   * - `any-length`: Returns a word with any length.
```
Comment (import-brain) [inline src/modules/lorem/index.ts:27]: Should we put this below the `@param options.strategy` line?

I think it would make more sense there.

**Comment by ST-DDT** [comment]
<details>
<summary><strong>Docs-Preview</strong> (Click to expand)</summary>

grafik

</details>

**Review by Shinigami92 — DISMISSED** [review]

**Review by ejcheng — DISMISSED** [review]

**Comment by Shinigami92** [comment]
Looks like needs a rebase

**Comment by ST-DDT** [comment]
Updated

**Review by Shinigami92 — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]
