### PR TITLE
infra: enable strictNullChecks in tsconfig

### LINKED ISSUE #1834: Turn on strictNullChecks in tsconfig
https://github.com/faker-js/faker/pull/651 partially activated strict mode, this flag was omitted at that time and should probably be turned on.

https://github.com/faker-js/faker/blob/c46c53948efaf9ccb2597f36954128f914b73179/tsconfig.json#L11

Related issues:

- https://github.com/faker-js/faker/pull/651
- https://github.com/faker-js/faker/issues/1835
- https://github.com/faker-js/faker/issues/1836
- https://github.com/faker-js/faker/issues/1837
- https://github.com/faker-js/faker/issues/1838

### LINKED ISSUE #2503: Using specific locales and calling prefix or jobTitle throws error: Calling `faker.helpers.arrayElement()` without arguments is no longer supported.
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

When using a specific locale and method `person.prefix` or `person.jobTitle` it throws an error: 

```
Calling `faker.helpers.arrayElement()` without arguments is no longer supported.
```

I suspect the issue is the locale data has empty/missing array which is passed into the helper method by prefix or jobTitle. 

#### Expected behaviour
I would expect this not to crash/throw an error. 

#### Effected locales
az
id_ID
ru
zh_CN
zh_TW

#### Solutions
1. All locales have an empty array set which is passed into arrayElement method
2. Allow arrayElement to be called with undefined

### Minimal reproduction code

https://codesandbox.io/s/sad-maxwell-m44x5y?file=/src/index.mjs

### Additional Context

There may be other locales and methods that are also effected by this too.

### Environment Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 76.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.1/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v20.8.1/bin/pnpm
  Browsers:
    Brave Browser: 118.1.59.122
    Safari: 17.0
  npmPackages:
    @faker-js/faker: ^8.2.0 => 8.2.0
```

### Which module system do you use?

- [X] CJS
- [X] ESM

### Used Package Manager

pnpm

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #1834

- #1834

### CODE REVIEW

File: docs/.vitepress/versions.ts [hunk 1]
```diff
@@ -23,8 +23,9 @@ function readOtherLatestReleaseTagNames(): string[] {
       }
       return acc;
     }, {});
+
```
Comment (ST-DDT) [inline docs/.vitepress/versions.ts:30]:
```suggestion
```

File: src/modules/date/index.ts [hunk 2]
```diff
@@ -387,14 +391,15 @@ export class SimpleDateModule {
         },
     legacyTo?: string | Date | number
   ): Date {
-    if (typeof options !== 'object' || options instanceof Date) {
+    if (options instanceof Date || typeof options !== 'object') {
```
Comment (ST-DDT) [inline src/modules/date/index.ts:391]: Flipping this somehow fixes an ts-error in line 405 🤷‍♂️ .

File: src/modules/person/index.ts [hunk 3]
```diff
@@ -97,7 +108,7 @@ export class PersonModule {
       this.faker.rawDefinitions.person ?? {};
 
     return selectDefinition(this.faker, this.faker.helpers.arrayElement, sex, {
-      generic: first_name,
+      generic: first_name ?? undefined,
```
Comment (ST-DDT) [inline src/modules/person/index.ts]:
```suggestion
      generic: first_name,
```

File: cypress/e2e/api.cy.ts [hunk 4]
```diff
@@ -34,7 +34,7 @@ describe('API Test', () => {
       cy.get('.api-group li').each(($el) => {
         const anchor = $el.find('a');
         const text = anchor.text();
-        const link = anchor.attr('href').split('#')[0];
+        const link = anchor.attr('href')!.split('#')[0];
```
Comment (xDivisionByZerox) [inline cypress/e2e/api.cy.ts]: I mena we wouldn't really activate this just to work around it again, would we?

```suggestion
        const link = anchor.attr('href')?.split('#')[0] ?? '';
```

File: src/modules/finance/index.ts [hunk 5]
```diff
@@ -1163,7 +1163,7 @@ export class FinanceModule {
 
     const result = `${ibanFormat.country}${checksum}${s}`;
 
-    return formatted ? result.match(/.{1,4}/g).join(' ') : result;
+    return formatted ? result.replace(/(.{4})(?=.)/g, '$1 ') : result;
```
Comment (ST-DDT) [inline src/modules/finance/index.ts]: Which is easier to read?

- `result.match(/.{1,4}/g)!.join(' ')`
- `result.replace(/(.{4})(?=.)/g, '$1 ')`
- `result.replace(/(.{4})/g, '$1 ').trimRight()`

The first seems to be the fastest (using unreliable online tests).

File: test/modules/finance_iban.spec.ts [hunk 6]
```diff
@@ -36,7 +36,7 @@ describe('finance_iban', () => {
 
           expect(iban).toSatisfy(validator.isIBAN);
 
-          const ibanFormatted = iban.match(/.{1,4}/g).join(' ');
+          const ibanFormatted = iban.match(/.{1,4}/g)!.join(' ');
```
Comment (ST-DDT) [inline test/modules/finance_iban.spec.ts]: Should I adjust the code here as well?

File: src/locales/ar/date/weekday.ts [hunk 7]
```diff
@@ -1,5 +1,13 @@
 export default {
-  abbr: null,
```
Comment (xDivisionByZerox) [inline src/locales/ar/date/weekday.ts]: Didn't we explicitly decide to allow `null` for "not appicable" in out locale data? I think we should have a look into our `LocaleDefinition` type before "fixing" those values. 

In the case:
Should we add conert the month property from `DateEntryDefinition` to `LocaleEntry<DateEntryDefinition>`? Or even better, should `LocaleEntry` recursivly apply itself to types which extend `object`? That why we only have to apply `LocaleEntry` ones to the actual `LocaleDefinition` type itself.

File: tsconfig.json [hunk 8]
```diff
@@ -9,7 +9,6 @@
     "stripInternal": true,
 
     // We need to disable these for now, and need to tackle them in another PR
-    "strictNullChecks": false,
```
Comment (ST-DDT) [inline tsconfig.json:12]: Is removing this correct, or do we have to set this to `true` instead?

**Comment by ST-DDT** [comment]
Ready for review.

File: tsconfig.json (hunk 8 above)
Comment (xDivisionByZerox) [reply tsconfig.json:12]: We have the `strict` property aboth that would usally include `strictNullChecks`. So removing it here enables it again. Kinda similar to what we doing with the unicorn plugin.

File: docs/.vitepress/versions.ts [hunk 9]
```diff
@@ -24,7 +24,7 @@ function readOtherLatestReleaseTagNames(): string[] {
       return acc;
     }, {});
   return Object.entries(latestReleaseTagNames)
-    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`))
+    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`)!)
```
Comment (xDivisionByZerox) [inline docs/.vitepress/versions.ts]:
```suggestion
    .map(([major, tags]) => semver.maxSatisfying(tags, `^${major}`))
    .filter((version): version is string => typeof version === 'string')
```

File: scripts/apidoc/fakerClass.ts [hunk 10]
```diff
@@ -62,7 +66,7 @@ async function processClass(
 function hasConstructor(clazz: DeclarationReflection): boolean {
   return clazz
     .getChildrenByKind(ReflectionKind.Constructor)
-    .some((constructor) => constructor.signatures.length > 0);
+    .some((constructor) => constructor.signatures!.length > 0);
```
Comment (xDivisionByZerox) [inline scripts/apidoc/fakerClass.ts]:
```suggestion
    .some((constructor) => (constructor.signatures?.length ?? 0) > 0);
```

File: src/modules/commerce/index.ts [hunk 11]
```diff
@@ -386,7 +386,7 @@ export class CommerceModule {
 
     const registrantLength = groupRules.find(
       ([rangeMaximum]) => elementValue <= rangeMaximum
-    )[1];
+    )![1];
```
Comment (xDivisionByZerox) [inline src/modules/commerce/index.ts]:
```suggestion
    ) ?? [0, 0])[1];
```

Sadly can't add lines which have not been touched. So I cant set the open bracket in line 387.
Alternitivly we could check if the `find` resolves to `undefined` and throw an error in that case. That would get rid of the non-null assertion.

File: src/modules/date/index.ts (hunk 2 above)
Comment (xDivisionByZerox) [reply src/modules/date/index.ts:391]: Because the last thing to resolve here is `typeof options !== 'object'` so if this fails `options` is definitly an object; if it doesn't fail ts can infer that `options` will definitly be an object after the block statement as well. This might sound stupid but the statement before TypeScript would have been able to tell that `options` was 100% a `Date`, but could say the same for `object`. 
Although, I cant tell you an example where that would happen. Propably some prototype shenanigan.

File: src/modules/date/index.ts [hunk 12]
```diff
@@ -387,14 +391,15 @@ export class SimpleDateModule {
...
       deprecated({
         deprecated: 'faker.date.between(from, to)',
         proposed: 'faker.date.between({ from, to })',
         since: '8.0',
         until: '9.0',
       });
-      options = { from: options, to: legacyTo };
+      // We use options as fallback for legacyTo avoid TS errors for unintended usage.
+      options = { from: options, to: legacyTo ?? options };
```
Comment (xDivisionByZerox) [inline src/modules/date/index.ts:399]: Can we extend the comment to remove this workaround in v9?

```suggestion
      // We use options as fallback for legacyTo avoid TS errors for unintended usage.
      // TODO: Remove in v9
      options = { from: options, to: legacyTo ?? options };
```

File: src/modules/date/index.ts [hunk 13]
```diff
@@ -1108,7 +1114,14 @@ export class DateModule extends SimpleDateModule {
...
 
-    return this.faker.helpers.arrayElement(source[type]);
+    const values = source[type];
+
+    if (values == null) {
+      // This should never happen due to the checks above, but TS doesn't know that
+      throw new FakerError(`No month values found for type '${type}'.`);
+    }
+
+    return this.faker.helpers.arrayElement(values);
```
Comment (xDivisionByZerox) [inline src/modules/date/index.ts]: Can't we simply this by letting `arrayElement` handle the "error tha is never possible"?

```suggestion
    return this.faker.helpers.arrayElement(source[type] ?? []);
```

File: src/modules/date/index.ts [hunk 14]
```diff
@@ -1298,6 +1311,13 @@ export class DateModule extends SimpleDateModule {
...
 
-    return this.faker.helpers.arrayElement(source[type]);
+    const values = source[type];
+
+    if (values == null) {
+      // This should never happen due to the checks above, but TS doesn't know that
+      throw new FakerError(`No weekday values found for type '${type}'.`);
+    }
+
+    return this.faker.helpers.arrayElement(values);
```
Comment (xDivisionByZerox) [inline src/modules/date/index.ts]: Same here?

```suggestion
    return this.faker.helpers.arrayElement(source[type] ?? []);
```

File: src/modules/finance/index.ts [hunk 15]
```diff
@@ -679,9 +679,9 @@ export class FinanceModule {
    */
   currencySymbol(): string {
     let symbol: string;
-    while (!symbol) {
+    do {
       symbol = this.currency().symbol;
-    }
+    } while (!symbol);
```
Comment (xDivisionByZerox) [inline src/modules/finance/index.ts]: I had to look up while this is even getting looped. We should make the check more percise since the symbol itself always exists (as an empty string). Alternatively we could update the `Currency` definition to allow optional or `null` values.

```suggestion
    } while (symbol.length === 0);
```

File: test/faker.spec.ts [hunk 16]
```diff
@@ -41,7 +41,7 @@ describe('faker', () => {
   describe('rawDefinitions', () => {
     it('locale rawDefinition accessibility', () => {
       // Metadata
-      expect(faker.rawDefinitions.metadata.title).toBeDefined();
+      expect(faker.rawDefinitions.metadata!.title).toBeDefined();
```
Comment (xDivisionByZerox) [inline test/faker.spec.ts]: I mean this literally checks for the value being defined. No need to assert non-null.

```suggestion
      expect(faker.rawDefinitions.metadata?.title).toBeDefined();
```

File: test/vitest-extensions.ts [hunk 17]
```diff
@@ -11,6 +11,7 @@ expect.extend({
     return {
       pass: uniqueDuplication.length !== 0,
       message: () =>
+        // @ts-expect-error: `isNot` is incorrectly inferred as `function`.
```
Comment (xDivisionByZerox) [inline test/vitest-extensions.ts]: Maybe default `isNot` to false in the destruction? But I don't really get why the `this` scope is infered incorrectly. A workaround is no longer required in TS  5.2.x, tho.

**Review by xDivisionByZerox — CHANGES_REQUESTED** [review]

File: src/locales/ar/date/weekday.ts (hunk 7 above)
Comment (ST-DDT) [reply src/locales/ar/date/weekday.ts]: The null is only supported on the second aka entry level. Everything below needs extra handling. We cannot extend the proxying downward because we also return complex objects.

File: docs/.vitepress/versions.ts (hunk 9 above)
Comment (ST-DDT) [reply docs/.vitepress/versions.ts]: The list is only there if there is at least one entry. So it is always there.
Not sure about the filter code that doesnt filter and only serves TS types.

File: scripts/apidoc/fakerClass.ts (hunk 10 above)
Comment (ST-DDT) [reply scripts/apidoc/fakerClass.ts]: I also considered this, but if there is a constructor without signature, I want to know that. Aka it shouldnt be possible unless typedoc changes their internal API.

File: src/modules/commerce/index.ts (hunk 11 above)
Comment (ST-DDT) [reply src/modules/commerce/index.ts]: This can never happen or only if the code itself is wrong. Why write code that would hide the bug and return potentially bad values?

File: src/modules/date/index.ts (hunk 12 above)
Comment (ST-DDT) [reply src/modules/date/index.ts:399]: The whole deprecation block will be gone in v9.

File: src/modules/date/index.ts (hunk 13 above)
Comment (ST-DDT) [reply src/modules/date/index.ts]: Sure, but then there wouldnt be a hint which data are actually missing.

File: test/faker.spec.ts (hunk 16 above)
Comment (ST-DDT) [reply test/faker.spec.ts]: AFAICT the ! is not an assertion, its a not null definition expression.
Or am I wrong?

File: cypress/e2e/api.cy.ts (hunk 4 above)
Comment (ST-DDT) [reply cypress/e2e/api.cy.ts]:
```suggestion
        const link = anchor.attr('href')?.split('#')[0] ?? 'MISSING';
```

File: test/vitest-extensions.ts (hunk 17 above)
Comment (ST-DDT) [reply test/vitest-extensions.ts]: TS claims that isNot is a function and always there thus the expression resolves to true always. But it is not.

File: test/faker.spec.ts (hunk 16 above)
Comment (xDivisionByZerox) [reply test/faker.spec.ts]: The name of the operator is [Non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator). It does only assert in a TS context tho.

The problem is that `faker.rawDefinitions.metadata` might be `null` or `undefined`. This will propably never happen, but TS doesn't know that. In general you should not use the the NNA operator. See [@typescript-eslint/no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion/)

File: test/vitest-extensions.ts (hunk 17 above)
Comment (xDivisionByZerox) [reply test/vitest-extensions.ts]: Thats why I proposed to default the the property in the destruction aboth: `const { isNot = false } = this;`. This would let TypeScript infer the type as `function | false` which ill not always resolve to true.

File: test/faker.spec.ts (hunk 16 above)
Comment (ST-DDT) [reply test/faker.spec.ts]: In the end it doesn't hurt to change this. Done.

File: test/vitest-extensions.ts (hunk 17 above)
Comment (ST-DDT) [reply test/vitest-extensions.ts]: Thanks for the explanation. Changed.

File: docs/.vitepress/versions.ts (hunk 9 above)
Comment (ST-DDT) [reply docs/.vitepress/versions.ts]: I found a way to avoid this code.

File: test/modules/finance_iban.spec.ts (hunk 6 above)
Comment (xDivisionByZerox) [reply test/modules/finance_iban.spec.ts]: Yes. We could consider removing this lines as they only check that we really implemented what we implemented. That would happen in another PR tho.

File: src/locales/ar/date/weekday.ts (hunk 7 above)
Comment (xDivisionByZerox) [reply src/locales/ar/date/weekday.ts]: We should extend the `abbr` property with a null parameter and include a comment about the condition which is required for it to possible be null. If those values ARE null the functions relying on the data should throw an error. Similar to the locale proxy.

File: src/modules/commerce/index.ts (hunk 11 above)
Comment (xDivisionByZerox) [reply src/modules/commerce/index.ts]: We will reconsider the implementation in a different PR.

File: src/modules/date/index.ts (hunk 13 above)
Comment (xDivisionByZerox) [reply src/modules/date/index.ts]: Will be considered by solving https://github.com/faker-js/faker/pull/2435#discussion_r1349312186.

File: src/modules/date/index.ts (hunk 14 above)
Comment (xDivisionByZerox) [reply src/modules/date/index.ts]: Will be considered by solving https://github.com/faker-js/faker/pull/2435#discussion_r1349312186.

File: src/modules/finance/index.ts (hunk 5 above)
Comment (ST-DDT) [reply src/modules/finance/index.ts]: Fixed

File: src/locales/ar/date/weekday.ts (hunk 7 above)
Comment (ST-DDT) [reply src/locales/ar/date/weekday.ts]: Fixed

File: src/modules/date/index.ts (hunk 13 above)
Comment (ST-DDT) [reply src/modules/date/index.ts]: Fixed

File: src/modules/date/index.ts (hunk 14 above)
Comment (ST-DDT) [reply src/modules/date/index.ts]: Fixed.

**Comment by ST-DDT** [comment]
Ready for review again. 😉

File: src/locale-proxy.ts [hunk 18]
```diff
@@ -54,6 +54,34 @@ export function createLocaleProxy(locale: LocaleDefinition): LocaleProxy {
...
+ * Checks that the value is not null or undefined and throws an error if it is.
+ *
+ * @param value The value to check.
+ * @param path The path to the locale data.
+ */
+export function assertLocaleData<T>(
+  value: T,
+  ...path: string[]
+): asserts value is NonNullable<T> {
+  if (value == null) {
```
Comment (xDivisionByZerox) [inline src/locale-proxy.ts]: Is this outer `if` really required?

Comment (ST-DDT) [reply src/locale-proxy.ts]: No, it is not. I just considered it as the fast path, but I'm not sure whether it has any performance implications.

Comment (xDivisionByZerox) [reply src/locale-proxy.ts]: I'd say it is obsolete here TBH.

Comment (ST-DDT) [reply src/locale-proxy.ts]: Changed.

File: src/modules/helpers/index.ts [hunk 19]
```diff
@@ -422,6 +422,7 @@ export class SimpleHelpersModule {
       const quantifierMin: string = token[2];
       const quantifierMax: string = token[3];
       const quantifierSymbol: string = token[4];
+      const tokenIndex: number = token.index!;
```
Comment (xDivisionByZerox) [inline src/modules/helpers/index.ts]: I thought a little bit about this. Can we not default this to `0`? Should we perhaps exit the `while` loop if it doesn't exist? Thats the two solutions I can think off. I dont really like using the NNAO here.

Comment (ST-DDT) [reply src/modules/helpers/index.ts]: We could switch from `string.match(regex)` to `regexp.exec(string)`.
That would fix that issue as well.

I don't think defaulting to 0 would do us any good. Maybe -1 or NaN so it explodes at the next usage instead doing something random.

Comment (ST-DDT) [reply src/modules/helpers/index.ts]: The index is always present, when the regex does not use the global flag.

Comment (xDivisionByZerox) [reply src/modules/helpers/index.ts]: > We could switch from string.match(regex) to regexp.exec(string).

How would you retrieve the index in that case? I'm a bit lost.

> I don't think defaulting to 0 would do us any good. Maybe -1 or NaN so it explodes at the next usage instead doing something random.

Well that works for me as well. ~~I would propably prefer `-1` tho.~~ We should use `NaN` as negative numbers behave differently on `String.prototype.slice`.

> The index is always present, when the regex does not use the global flag.

Where did you find this information? I was searching for this when I wrote my previous comment but didn't find anything. :(

Comment (ST-DDT) [reply src/modules/helpers/index.ts]: > > We could switch from string.match(regex) to regexp.exec(string).
> 
> How would you retrieve the index in that case? I'm a bit lost.

In that case the index property is always there.

Comment (ST-DDT) [reply src/modules/helpers/index.ts]: > > The index is always present, when the regex does not use the global flag.
> 
> Where did you find this information? I was searching for this when I wrote my previous comment but didn't find anything. :(

Try and error + some stackoverflow.

Comment (ST-DDT) [reply src/modules/helpers/index.ts]: FFR: https://typescript-eslint.io/rules/prefer-regexp-exec/

**Comment by ST-DDT** [comment]
See #2466 for a regex related NNA `!` relief.

- #2466 

(Technically not blocking, but might be worth merging first)

**Comment by ST-DDT** [comment]
Ready to review again. 😉

File: src/modules/helpers/index.ts [hunk 20]
```diff
@@ -1121,7 +1121,7 @@ export class SimpleHelpersModule {
     ) => RecordKey,
   >(
     method: TMethod,
-    args: Parameters<TMethod> = [] as Parameters<TMethod>,
+    args: Parameters<TMethod> = [] as unknown as Parameters<TMethod>,
```
Comment (xDivisionByZerox) [inline src/modules/helpers/index.ts:1123]: We could probably "fix" this casting by some generic making but as the function is deprecated anyway I'd not waste time optimizing this.

**Review by xDivisionByZerox — DISMISSED** [review]

File: src/modules/helpers/index.ts (hunk 20 above)
Comment (ST-DDT) [reply src/modules/helpers/index.ts:1123]: Having a default here is basically a lie because some parameters may be required... But that is something for a different PR if at all.

**Review by xDivisionByZerox — DISMISSED** [review]

File: src/modules/date/index.ts [hunk 21]
```diff
@@ -1286,6 +1287,32 @@ export class DateModule extends SimpleDateModule {
...
   }
 }
+
+/**
+ *
+ * @param options asd
+ * @param options.deprecated as
+ * @param options.replacement asd
+ */
+export function demo(
```
Comment (xDivisionByZerox) [inline src/modules/date/index.ts]: This is propably not supposed to be here?

File: src/modules/date/index.ts [hunk 22]
```diff
@@ -1286,6 +1287,32 @@ export class DateModule extends SimpleDateModule {
...
+  } = {}
+): boolean {
+  const {
+    // eslint-disable-next-line deprecation/deprecation
+    deprecated = false,
+    // eslint-disable-next-line deprecation/deprecation
+    replacement = deprecated,
+  } = options;
+  return replacement;
+}
```
Comment (ST-DDT) [inline src/modules/date/index.ts]:
```suggestion

```

File: src/modules/date/index.ts (hunk 21 above)
Comment (ST-DDT) [reply src/modules/date/index.ts]: Yeah, I used that code to test some cases for the deprecation warnings that for some reason appeared as part of this PR.

- https://github.com/gund/eslint-plugin-deprecation/issues/74
- https://github.com/gund/eslint-plugin-deprecation/issues/75

**Review by xDivisionByZerox — DISMISSED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Comment by ST-DDT** [comment]
**Team Decision**

This is largely unchanged since creation and has been approved for more than a week (if you ignore the minor merge conflicts).
