### PR TITLE
fix(number): improve float generation for precisions of form 10^-n

### LINKED ISSUE #331: datatype.number does not always generate numbers with expected precision
### Describe the bug

Due to the limitations of float arithmetics the `precision` param is not always well reflected in the generated output.

### Reproduction

```
> faker.datatype.number({ precision: 0.01 })
64246.18
> faker.datatype.number({ precision: 0.001 })
75598.72
> faker.datatype.number({ precision: 0.0001 })
15719.824
> faker.datatype.number({ precision: 0.00001 })
57268.07910000001
```

### Additional Info

Suggested solution would be to use a better math library offering arbitrary-precision decimal arithmetic, eg. https://www.npmjs.com/package/big.js

### LINKED ISSUE #2567: Generating a float with precision of 0.00001 gives larger precision number
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

When trying to generate a float using **faker.number.float({ precision: 0.00001 })**, the generated float generates a number with more than 5 decimal place values after the decimal point. Generated float values where precision is set to 0.1 to 0.0001, and 0.000001 and greater are consistently working. 

### Minimal reproduction code

https://runkit.com/embed/g86r0jyau1rk

### Additional Context

fake

Using faker-js to write playwright tests; example shows a generated value logged out where it was set to **faker.number.float({ max: 99999.99999, precision: 0.00001 })**.

### Environment Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 6.67 GB / 15.46 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 3.6.3 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  npmPackages:
    @faker-js/faker: ^8.0.2 => 8.0.2
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #2567

Changes the way that the 1/precision is calculated in faker.number.float() using Math.log10 and Math.pow

This ensures that if precision is 0.00001, you get exactly 100000 for example, not 99999.99999999999

### CODE REVIEW

**Comment by matthewmayer** [comment]
Note this obviously conflicts with #2564, probably easiest to merge that first since it touches more code

File: src/modules/number/index.ts [hunk 1]
```diff
@@ -150,7 +150,9 @@ export class NumberModule extends SimpleModuleBase {
         throw new FakerError(`Precision should be greater than 0.`);
       }
 
-      const factor = 1 / precision;
+      const factor = Number.isInteger(Math.log10(precision))
+        ? Math.pow(10, -Math.log10(precision)) //mathematically this is the same as 1/precision, however it helpfully gives integer values for all precisions of the form 10^-n
```
Comment (ST-DDT) [inline src/modules/number/index.ts]: Maybe cache the log10 result?

File: test/modules/number.spec.ts [hunk 2]
```diff
@@ -270,6 +286,17 @@ describe('number', () => {
...
       });
 
+      it('provides numbers with an exact precision of 0.00001', () => {
+        for (let i = 0; i < 100; i++) {
+          const actual = faker.number.float({
+            min: 0.5,
+            max: 0.99,
+            precision: 0.00001,
+          });
+          expect(actual).toBe(Number(actual.toFixed(5)));
```
Comment (ST-DDT) [inline test/modules/number.spec.ts]: Maybe do this test for all values `10**x where 10 > x > -10 and x is int` instead of just testing some magic value.

**Comment by ST-DDT** [comment]
And thanks for tackling this ❤️

File: test/modules/number.spec.ts (hunk 2 above)
Comment (matthewmayer) [reply test/modules/number.spec.ts]: added it for all negative x

File: test/modules/number.spec.ts [hunk 3]
```diff
@@ -275,25 +275,16 @@ describe('number', () => {
...
-      it('provides numbers with an exact precision of 0.00001', () => {
-        for (let i = 0; i < 100; i++) {
-          const actual = faker.number.float({
-            min: 0.5,
-            max: 0.99,
-            precision: 0.00001,
-          });
-          expect(actual).toBe(Number(actual.toFixed(5)));
+      it('provides numbers with an exact precision of 10^-x for x=1 to 18', () => {
+        for (let factor = 1; factor <= 18; factor++) {
```
Comment (ST-DDT) [inline test/modules/number.spec.ts]: Please use it.each for the outer loop and also check factors with negative and zero values.
(They might need a different check, so we could potentially put them in a separate it block.)

Lastly I'm not sure about calling this factor IMO this should be called exponent (and have its value negated) or digits (to match toFixed).

Comment (matthewmayer) [reply test/modules/number.spec.ts]: im not sure checking precisions like 1, 10, 100 is very useful, after all if you are doing

faker.number.float({min:0, max:1000, precision:100}) would you not be better served by using faker.number.int() ?

Comment (ST-DDT) [reply test/modules/number.spec.ts]: Faker.number.int doesnt have a precision parameter.
I'll think about it some more.

Comment (matthewmayer) [reply test/modules/number.spec.ts]: `faker.number.float({min:0, max:1000, precision:100})` is just `100 * faker.number.int({min:0, max:10})`

Comment (ST-DDT) [reply test/modules/number.spec.ts]: So is `faker.number.float({min:0, max:1, precision:0.1})` just `0.1 * faker.number.int({min:0, max:10})`

Comment (matthewmayer) [reply test/modules/number.spec.ts]: Basically yes. The problem is that when you multiply by numbers like 0.00001 in JS you get these weird floating point errors which we are trying to avoid.

Comment (matthewmayer) [reply test/modules/number.spec.ts]: We could add multipleOf for int too for symmetry

Comment (ST-DDT) [reply test/modules/number.spec.ts]: I also thought about that and we should do that, although in a different PR.

File: src/modules/number/index.ts [hunk 4]
```diff
@@ -150,7 +150,10 @@ export class NumberModule extends SimpleModuleBase {
         throw new FakerError(`Precision should be greater than 0.`);
       }
 
-      const factor = 1 / precision;
+      const logPrecision = Math.log10(precision);
+      const factor = Number.isInteger(logPrecision)
+        ? Math.pow(10, -logPrecision) //mathematically this is the same as 1/precision, however it helpfully gives integer values for all precisions of the form 10^-n
```
Comment (ST-DDT) [inline src/modules/number/index.ts]: Please move the comment to the front, maybe even another line up as it refers to the entire block. 

```suggestion
      // Workaround to get integer values for the reverse of all precisions of the form 10^-n
      const factor = Number.isInteger(logPrecision)
        ? (10 ** -logPrecision)
```

Also I prefer `**` over Math.pow (We should probably enable [prefer-exponentiation-operator](https://eslint.org/docs/latest/rules/prefer-exponentiation-operator) too)
Not sure whether the parenthesis are needed here.

**Review by ST-DDT — COMMENTED** [review]
Sorry, I didn't have enough free time to look at the precision behavior yet.

File: test/modules/number.spec.ts [hunk 5]
```diff
@@ -259,17 +259,37 @@ describe('number', () => {
...
+                precision: 0.2,
+              })
+            )
+          ),
+        ].sort();
+
+        expect(results).toEqual([0, 0.2, 0.4]);
       });
 
+      const exponents = Array.from({ length: 18 }, (_, i) => i + 1);
```
Comment (ST-DDT) [inline test/modules/number.spec.ts]: Please use our `times(x)` util for that.

https://github.com/faker-js/faker/blob/8996a7430b9bdc3a86cc2d972c4f743a301cc5c6/test/support/times.ts#L8-L10

File: test/modules/number.spec.ts [hunk 6]
```diff
@@ -259,17 +259,37 @@ describe('number', () => {
...
+      it.each(exponents)(
+        `provides numbers with an exact precision of 10^-%d`,
+        (exponent) => {
+          for (let i = 0; i < 100; i++) {
+            const actual = faker.number.float({
+              min: 0.5,
+              max: 0.99,
+              precision: Math.pow(10, -exponent),
```
Comment (ST-DDT) [inline test/modules/number.spec.ts]: Please also use `**` here.

File: src/modules/number/index.ts (hunk 4 above)
Comment (ST-DDT) [reply src/modules/number/index.ts]: I created #2585 to enable that rule.

- #2585

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
Thanks for addressing all my comments 👍
