### PR TITLE
fix(commerce): return fractional prices

### LINKED ISSUE #350: Commerce price does not return fractional currency prices
### Describe the bug

`faker.commerce.price()` always returns a value with full price. 
=> `245.00` , `842.00`

It would be nice if it could also generate prices with fractional currency prices
=> `245.71` , `842.45`

Also if invalid prices ranges are given, then the returned prices does not respect the decimal places paramter.

### Reproduction

`faker.commerce.price()` => `245.00`
`faker.commerce.price(-1)` => `0`

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by ejcheng**
closes #350

### CODE REVIEW

**Review by ST-DDT — DISMISSED** [review]

**Review by xDivisionByZerox — DISMISSED** [review]

**Review by matthewmayer — CHANGES_REQUESTED** [review]
This doesn't seem very realistic, e-commerce sites don't typically have random numbers of cents on a price for items above $100. It's more common to round to a nice number like .00 or .95 or .99

image

**Comment by ST-DDT** [comment]
There are some prices that are like 1.20€ like a serving of ice.

**Comment by ST-DDT** [comment]
Amazon Prime Video today: 
grafik

But I must admit a price like 10.09€ is rare.

**Comment by matthewmayer** [comment]
I think a more realistic algorithm for prices might be:
* Generate the raw price
* Round to 2 or 3 significant digits (e.g. 1.23 or 12.30 or 123.00 or 1230.00)
* Optionally deduct 0.01 or 0.05

**Comment by ejcheng** [comment]
> There are some prices that are like 1.20€ like a serving of ice.

Also, when you convert a price from one currency to another, you often get something like "$120.14".

**Comment by ST-DDT** [comment]
**Team Decision**

We will alter the distribution to favor the special numbers by using faker.helpers.weightedArrayElement for the last decimal digit.

- 9: weight: 5
- 5: weight: 3
- 0: weight: 1
- random(0-9): weight: 1

If the dec is zero we will skip this behavior.

**Review by ST-DDT — APPROVED** [review]

**Review by matthewmayer — CHANGES_REQUESTED** [review]
While this is an improvement, these prices still don't seem to be that realistic for a typical e-commerce site. 
```
faker.helpers.multiple(x=>faker.commerce.price(), {count:100})
[
  '820.09', '579.51', '33.55',  '852.35', '895.00', '177.55',
  '268.10', '506.25', '808.19', '473.33', '46.55',  '76.95',
  '767.89', '268.39', '575.25', '826.20', '315.69', '696.99',
  '41.40',  '969.69', '213.70', '518.15', '797.59', '786.95',
  '65.69',  '931.92', '553.30', '493.65', '174.99', '187.10',
  '778.49', '950.00', '633.40', '504.19', '221.79', '34.69',
  '717.75', '980.06', '207.55', '988.15', '498.39', '299.95',
  '267.72', '955.59', '276.47', '513.59', '16.99',  '300.19',
  '670.53', '9.39',   '908.79', '802.59', '397.59', '546.09',
  '25.69',  '475.09', '215.29', '240.89', '477.10', '919.55',
  '446.58', '239.45', '845.55', '826.70', '674.79', '22.69',
  '674.19', '508.95', '956.69', '733.32', '475.19', '21.49',
  '619.79', '84.69',  '619.89', '791.50', '880.19', '620.69',
  '93.90',  '443.49', '288.69', '813.81', '662.89', '232.95',
  '890.45', '251.89', '841.99', '795.40', '541.08', '715.89',
  '792.19', '646.99', '176.49', '782.49', '659.79', '482.65',
  '154.40', '455.39', '188.59', '894.79'
]
```

I think part of the issue is that the default max is 1000, and you're unlikely to find prices above 100 with 5 significant digits like 820.09.

Could consider 
- Changing the default max to 100
or
- Overriding the last two digits using weightedArrayElements, favoring .00, .95, .99 and 10% random.

**Comment by ejcheng** [comment]
> While this is an improvement, these prices still don't seem to be that realistic for a typical e-commerce site.
> 
> ```
> faker.helpers.multiple(x=>faker.commerce.price(), {count:100})
> [
>   '820.09', '579.51', '33.55',  '852.35', '895.00', '177.55',
>   '268.10', '506.25', '808.19', '473.33', '46.55',  '76.95',
>   '767.89', '268.39', '575.25', '826.20', '315.69', '696.99',
>   '41.40',  '969.69', '213.70', '518.15', '797.59', '786.95',
>   '65.69',  '931.92', '553.30', '493.65', '174.99', '187.10',
>   '778.49', '950.00', '633.40', '504.19', '221.79', '34.69',
>   '717.75', '980.06', '207.55', '988.15', '498.39', '299.95',
>   '267.72', '955.59', '276.47', '513.59', '16.99',  '300.19',
>   '670.53', '9.39',   '908.79', '802.59', '397.59', '546.09',
>   '25.69',  '475.09', '215.29', '240.89', '477.10', '919.55',
>   '446.58', '239.45', '845.55', '826.70', '674.79', '22.69',
>   '674.19', '508.95', '956.69', '733.32', '475.19', '21.49',
>   '619.79', '84.69',  '619.89', '791.50', '880.19', '620.69',
>   '93.90',  '443.49', '288.69', '813.81', '662.89', '232.95',
>   '890.45', '251.89', '841.99', '795.40', '541.08', '715.89',
>   '792.19', '646.99', '176.49', '782.49', '659.79', '482.65',
>   '154.40', '455.39', '188.59', '894.79'
> ]
> ```
> 
> I think part of the issue is that the default max is 1000, and you're unlikely to find prices above 100 with 5 significant digits like 820.09.
> 
> Could consider
> 
> * Changing the default max to 100
>   or
> * Overriding the last two digits using weightedArrayElements, favoring .00, .95, .99 and 10% random.

I'm in favor of overriding the last two digits.

**Comment by ST-DDT** [comment]
The last two decimal digits or the last two significant digits?

**Review by ST-DDT — CHANGES_REQUESTED** [review]
We might need more tests for the new behavior:

````ts
faker.seed(4);
faker.commerce.price({ dec: 2, min: 1, max: 1.1 }); // 1.15 ⚠️ 
````

We should probably start documenting the new behavior in the js docs and potentially add an `@see` to `faker.number.float`

**Comment by ejcheng** [comment]
> The last two decimal digits or the last two significant digits?

I would think decimal digits, but I'm open to significant digits as well.

**Comment by matthewmayer** [comment]
> We might need more tests for the new behavior:
> 
> ```ts
> faker.seed(4);
> faker.commerce.price({ dec: 2, min: 1, max: 1.1 }); // 1.15 ⚠️ 
> ```

To avoid this I'd do a final sanity check that the value with the replaced cents is still within min...max, and if it isn't use the original value instead.

File: src/modules/number/index.ts [hunk 1]
```diff
@@ -98,6 +98,8 @@ export class NumberModule {
    * @param options.precision Precision of the generated number, for example `0.01` will round to 2 decimal points.
    * If precision is passed, the upper bound is inclusive.
    *
+   * @see faker.commerce.price() for prices
+   *
```
Comment (ST-DDT) [inline src/modules/number/index.ts]: IMO we shouldn't link from float to prices because there are a LOT of things that are also floats.

File: src/modules/commerce/index.ts [hunk 2]
```diff
@@ -270,10 +298,39 @@ export class CommerceModule {
...
+      { weight: 3, value: '5' },
+      { weight: 1, value: '0' },
+      {
+        weight: 1,
+        value: this.faker.number.int({ min: 0, max: 9 }).toString(),
+      },
+    ]);
+
+    if (
+      parseFloat(randValueString.replace(/\d$/, lastDigit)) <= max &&
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]: I would probably store that value somewhere instead of recalculating it 3 times.

File: test/modules/commerce.spec.ts [hunk 3]
```diff
@@ -124,14 +125,28 @@ describe('commerce', () => {
...
           const price = faker.commerce.price(100, 100, 0);
 
           expect(price).toBeTruthy();
-          expect(price, 'the price should be equal 100').toBe('100');
+          expect(price, 'the price should equal 100').toBe('100');
+        });
+
+        it('should return decimal values between min and max', () => {
+          const result = faker.helpers.multiple(
+            () => faker.commerce.price(1, 1.1, 2),
```
Comment (ST-DDT) [inline test/modules/commerce.spec.ts:140]: Maybe use a price min that is also a float?

File: src/modules/commerce/index.ts [hunk 4]
```diff
@@ -270,10 +298,40 @@ export class CommerceModule {
...
+      min,
+      max,
+      precision: (1 / 10) ** dec,
+    });
+
+    if (dec === 0) {
+      return `${symbol}${randValue.toFixed(dec)}`;
+    }
+
+    const randValueString = randValue.toFixed(dec).toString();
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]: AFAICT toFixed already returns a string. So there shouldn't be a need to call toString().

File: src/modules/commerce/index.ts [hunk 5]
```diff
@@ -270,10 +298,40 @@ export class CommerceModule {
...
+    const lastDigit = this.faker.helpers.weightedArrayElement([
+      { weight: 5, value: '9' },
+      { weight: 3, value: '5' },
+      { weight: 1, value: '0' },
+      {
+        weight: 1,
+        value: this.faker.number.int({ min: 0, max: 9 }).toString(),
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]: I'm not sure myself with this suggestion:

Have you tried using faker.string.numeric(1) instead?

File: src/modules/commerce/index.ts [hunk 6]
```diff
@@ -270,10 +298,40 @@ export class CommerceModule {
...
+      },
+    ]);
+
+    const parsedNewRandValue = Number.parseFloat(
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]: I'm not really happy with the name of the variable, but don't have a better suggestion for now.

Comment (ejcheng) [reply src/modules/commerce/index.ts]: Yeah, I thought this variable was named badly too, but I couldn't come up with anything better.

Comment (ejcheng) [reply src/modules/commerce/index.ts]: > I'm not really happy with the name of the variable, but don't have a better suggestion for now.

Just thought of this: would `parsed` be a good idea for this variable name? Or is it too vague?

File: src/modules/commerce/index.ts (hunk 5 above)
Comment (ejcheng) [reply src/modules/commerce/index.ts]: > I'm not sure myself with this suggestion:
> 
> Have you tried using faker.string.numeric(1) instead?

This causes tests to fail because it doesn't generate enough decimal places 🤔

**Comment by ST-DDT** [comment]
How about changing how the method is implemented.

````ts
const suffix: number = switch ...;
const random = faker.number.float(..., 1/10**(dec-1)) + suffix / 10 ** dec);
const clamped = Math.min....

return `${symbol}${clamped}`;
````

**Comment by ejcheng** [comment]
> How about changing how the method is implemented.
> 
> ```ts
> const suffix: number = switch ...;
> const random = faker.number.float(..., 1/10**(dec-1)) + suffix / 10 ** dec);
> const clamped = Math....
> 
> return `${symbol}${clamped}`;
> ```

Sorry, what is `suffix`?

**Comment by ST-DDT** [comment]
> Sorry, what is `suffix`?

The `lastDigit`. Instead of generating it, we omit it in the number generation and mathematically add it.

dec = 2
lastDigit = switch ...; // => 9 ( * 10^-2)
generated = faker.number.float(precision: 10^-1); // => 12.1
combined => "$12.19"

File: src/modules/commerce/index.ts [hunk 7]
```diff
@@ -265,10 +293,39 @@ export class CommerceModule extends ModuleBase {
...
+
+    const generated = this.faker.number.float({
+      min,
+      max,
+      precision: (1 / 10) ** (dec - 1),
+    });
+
+    if (dec === 0) {
+      return `${symbol}${generated.toFixed(dec)}`;
+    }
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts:329]: IMO this doesn't saves much processing power, and having generated and lastDigit closer together helps understanding what it does. But that might be just me.
What do the others think?

File: src/modules/commerce/index.ts [hunk 8]
```diff
@@ -213,6 +234,13 @@ export class CommerceModule extends ModuleBase {
   /**
    * Generates a price between min and max (inclusive).
    *
+   * To better represent real-world prices, when `options.dec` is greater than 0, the final decimal digit in the returned string will be generated as follows:
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]:
```suggestion
   * To better represent real-world prices, when `options.dec` is greater than `0`, the final decimal digit in the returned string will be generated as follows:
```

File: src/modules/commerce/index.ts [hunk 9]
```diff
@@ -213,6 +234,13 @@ export class CommerceModule extends ModuleBase {
...
+   *
+   * - 50% of the time: '9'
+   * - 30% of the time: '5'
+   * - 10% of the time: '0'
+   * - 10% of the time: a random digit from 0-9
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]:
```suggestion
   * - 50% of the time: `9`
   * - 30% of the time: `5`
   * - 10% of the time: `0`
   * - 10% of the time: a random digit from `0` to `9`
```

**Review by ST-DDT — DISMISSED** [review]

**Comment by matthewmayer** [comment]
I'm still in favour of overriding the last two digits per my earlier review for more realistic prices.

**Comment by ST-DDT** [comment]
**Team Decision**

- For now we stay with a single altered digit.
- Before we touch it again we should do some research and maybe refactor the entire method to produce plausible prices without the need for the dec parameter.
- @ST-DDT will create an issue to rethink the price method
- "ChatGpt also doesn't think the 9s are important to include in the algorithm"

**Comment by ST-DDT** [comment]
Please add a test for:

`faker.commerce.price({ min: 0.001, max: 0.009, dec: 3 })`

Maybe fix it by wrapping the 

````ts
faker.number.float({
    min,
    max,
    precision: (1 / 10) ** (dec - 1),
  })
````

with a try catch

````ts
try {
  generated = ...
} catch {
  return faker.number.float({
    min,
    max,
    precision: (1 / 10) ** dec,
  });
}
````

File: src/modules/commerce/index.ts [hunk 10]
```diff
@@ -286,10 +314,49 @@ export class CommerceModule extends ModuleBase {
...
+    let generated: number;
+
+    try {
+      generated = this.faker.number.float({
+        min,
+        max,
+        precision: (1 / 10) ** (dec - 1),
+      });
+    } catch {
+      generated = this.faker.number.float({
```
Comment (ST-DDT) [inline src/modules/commerce/index.ts]: This has the side effect of not returning "price"-like values.
I think I have to think about it some more.

Comment (ST-DDT) [reply src/modules/commerce/index.ts]: IMO we should have some code that removes/substracts the least significant digit and then adds the replacement instead. That would be easier to read than my previous suggestion and is also be safe/easier, if we want to replace two digits in the future.

````ts
const oldLastDigit = (generated * 10 ** dec) % 10;
const newLastDigit = ...

combined = generated - oldLastDigit + newLastDigit;
...
````

Sorry, that it took me so long to come up with this idea.

**Comment by ST-DDT** [comment]
@import-brain Could you please update this PR or should we take it over?

**Comment by ejcheng** [comment]
> @import-brain Could you please update this PR or should we take it over?

@ST-DDT Could you please take this over?

**Comment by ST-DDT** [comment]
Sure no problem. This might take a bit though.

**Comment by ST-DDT** [comment]
Here a few prices that are returned by the price method:

<details>
<summary>Summary</summary>

Last Digit | Occurrences
----------- | ---------
0 | 13
1 | 0
2 | 1
3 | 1
4 | 2
5 | 30
6 | 1
7 | 1
8 | 2
9 | 49

</details>

<details>
<summary>Values</summary>

Price | Last Digit
------ | ---------
278.39 | 9
224.59 | 9
171.99 | 9
968.26 | 6
832.10 | 0
911.79 | 9
345.35 | 5
842.69 | 9
636.79 | 9
325.29 | 9
666.80 | 0
891.55 | 5
897.49 | 9
377.09 | 9
731.65 | 5
821.55 | 5
650.40 | 0
595.09 | 9
268.18 | 8
461.00 | 0
188.25 | 5
915.30 | 0
483.49 | 9
1.19 | 9
203.95 | 5
611.29 | 9
546.49 | 9
297.95 | 5
759.49 | 9
344.69 | 9
388.89 | 9
898.15 | 5
319.95 | 5
99.25 | 5
399.69 | 9
269.45 | 5
562.29 | 9
336.45 | 5
628.39 | 9
24.99 | 9
89.65 | 5
380.05 | 5
183.99 | 9
647.03 | 3
896.95 | 5
37.45 | 5
581.39 | 9
70.79 | 9
281.10 | 0
878.29 | 9
838.05 | 5
940.95 | 5
692.09 | 9
938.20 | 0
936.89 | 9
339.45 | 5
663.55 | 5
664.19 | 9
663.59 | 9
234.55 | 5
609.69 | 9
817.09 | 9
448.55 | 5
755.69 | 9
514.15 | 5
406.72 | 2
368.75 | 5
375.50 | 0
377.60 | 0
633.69 | 9
813.09 | 9
281.39 | 9
834.69 | 9
639.95 | 5
729.39 | 9
91.50 | 0
497.29 | 9
281.49 | 9
771.09 | 9
803.69 | 9
159.85 | 5
386.79 | 9
738.77 | 7
442.85 | 5
210.74 | 4
569.78 | 8
171.84 | 4
206.19 | 9
732.79 | 9
305.89 | 9
181.55 | 5
311.39 | 9
694.30 | 0
413.45 | 5
317.80 | 0
483.20 | 0
599.19 | 9
765.69 | 9
34.89 | 9
507.65 | 5

</details>

**Comment by ST-DDT** [comment]
Ready for review

**Review by ST-DDT — DISMISSED** [review]

**Review by ST-DDT — DISMISSED** [review]

**Comment by matthewmayer** [comment]
While it's not strictly a breaking change I think it's worth a mention in the migration guide given that it changes the behavior of the method.

**Review by ST-DDT — APPROVED** [review]

**Comment by ST-DDT** [comment]
> While it's not strictly a breaking change I think it's worth a mention in the migration guide given that it changes the behavior of the method.

Added

**Review by matthewmayer — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]
