### PR TITLE
docs: fix mersenne rand min max confusion

### LINKED ISSUE #775: Small issue with mersenne jsdoc
### Describe the bug

https://fakerjs.dev/api/mersenne.html#rand

In the examples, it says ```faker.mersenne.rand(500, 1000)```. However, the ```max``` parameter is listed first. I saw the code on how we got around listing ```max``` first (L33 to L37 of mersenne.ts), but is there any possible way we could improve the mersenne jsdoc examples? Could be a bit confusing, considering ```max``` is shown first in the function signature.

### Reproduction

faker.mersenne.rand(500, 1000)

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by gregoriomario**
although mersenne automatically swap the value if min is bigger than max, but it's a good practice to clear out the confusion.

Fix #775

### CODE REVIEW

File: src/mersenne.ts [hunk 1]
```diff
@@ -20,14 +20,14 @@ export class Mersenne {
   }
 
   /**
-   * Generates a random number between `[min, max)`.
+   * Generates a random number between `[max, min)`.
```
Comment (import-brain) [inline src/mersenne.ts:23]:
```suggestion
   * Generates a random number between `[min, max)`.
```
I think this should be changed back to what it was before (as seen in the suggestion block). The original description said that the function generates a number with an inclusive lower bound of ```min``` and an exclusive upper bound of ```max```, so this change will change the meaning of the JSDoc. Also, we should probably discuss putting a "max is first param" text in the JSDoc, but I'm not sure what format that would take.

**Review by import-brain — CHANGES_REQUESTED** [review]

File: src/mersenne.ts (hunk 1 above)
Comment (gregoriomario) [reply src/mersenne.ts:23]: I've been thinking about this too, which one should we change to clear out the confusion. Is it the docs that's inconsistent with the implemenetation of the param, or is it the param which might be better if we put min first instead of max. 

Maybe it's better to fix the param and keep the docs as it is before, but I'm not sure about this. Wdyt? 🤔

Comment (import-brain) [reply src/mersenne.ts:23]: I think fixing the param itself would be a breaking API change, so we should just change the doc. @Shinigami92 @ST-DDT @pkuczynski What do you think?

Comment (pkuczynski) [reply src/mersenne.ts:23]: Yes, this would be a breaking change so quite problematic...

Comment (ST-DDT) [reply src/mersenne.ts:23]: For now, please only the jsdocs please.

File: src/mersenne.ts [hunk 2]
```diff
@@ -20,14 +20,14 @@ export class Mersenne {
...
    *
    * @param max The maximum number. Defaults to `0`.
    * @param min The minimum number. Defaults to `32768`.
    *
    * @example
    * faker.mersenne.rand() // 15515
-   * faker.mersenne.rand(500, 1000) // 578
+   * faker.mersenne.rand(1000, 500) // 578
```
Comment (Shinigami92) [inline src/mersenne.ts:30]: Seems the "example" not wrong, should we just add another line?

File: src/mersenne.ts (hunk 1 above)
Comment (Shinigami92) [inline src/mersenne.ts:23]: Please re-check if the math symbols are correct (in-/ex-clusive)

**Review by Shinigami92 — COMMENTED** [review]
I assume it was implemented with max as first param, so that a user can use it with `faker.mersenne.rand(6)` so without a min argument and it just has a default min = 0

File: src/mersenne.ts (hunk 2 above)
Comment (Shinigami92) [reply src/mersenne.ts:30]: I take somewhat back my statement

max is in first place so it can potentially used without providing manually a min argument
I personally don't like that kind of parameter usage and would like to call it with options instead of two params, but that is not related to this PR 🤷

**Review by Shinigami92 — APPROVED** [review]

File: src/mersenne.ts [hunk 3]
```diff
@@ -20,14 +20,14 @@ export class Mersenne {
   }
 
   /**
-   * Generates a random number between `[min, max)`.
+   * Generates a random number between `[max, min)`.
    *
    * @param max The maximum number. Defaults to `0`.
    * @param min The minimum number. Defaults to `32768`.
```
Comment (Shinigami92) [inline src/mersenne.ts:26]: The default values are also wrong here 🤔 are they?

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Review by ST-DDT — APPROVED** [review]

**Review by import-brain — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]
