### PR TITLE
fix(date): ensures correct range for birthdate

### LINKED ISSUE #2534: Birthdate with default values return age less than 18
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

I was running into flaky tests in my application, and narrowed it down to faker's `date.birthdate` method.

According to the docs:

>The options to use to generate the birthdate. If no options are set, an age between 18 and 80 (inclusive) is generated.

But there are times that an age less than 18 years old is generated. This does not happen every time, but I was able to get a specific seed and refDate to reproduce the issue.

### Minimal reproduction code

https://stackblitz.com/edit/vitest-dev-vitest-md9oj6?file=test%2Fsuite.test.ts

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 65.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.123
    Edge: 119.0.2151.46
  npmPackages:
    @faker-js/faker: ^8.2.0 => 8.2.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by mumumilk**
fixes #2534

### CODE REVIEW

File: src/modules/date/index.ts [hunk 1]
```diff
@@ -886,10 +888,13 @@ export class SimpleDateModule extends SimpleModuleBase {
     } else {
       // Avoid generating dates the first and last date of the year
       // to avoid running into other years depending on the timezone.
-      min = new Date(Date.UTC(0, 0, 2)).setUTCFullYear(
+      const minDay = refMonth === 0 && refDay === 1 ? 2 : refDay;
+      const maxDay = refMonth === 11 && refDay === 31 ? 30 : refDay;
+
+      min = new Date(Date.UTC(0, refMonth, minDay)).setUTCFullYear(
```
Comment (ST-DDT) [inline src/modules/date/index.ts]: These interfere with the usage when specifying min and max.
Because then it can only return the current date.

**Review by ST-DDT — CHANGES_REQUESTED** [review]

**Comment by ST-DDT** [comment]
Please add these tests:

https://github.com/faker-js/faker/blob/022fa540106e25818936c6ebfe8d10fe9ee15b30/test/modules/date.spec.ts#L576-L603

File: src/modules/date/index.ts (hunk 1 above)
Comment (mumumilk) [reply src/modules/date/index.ts]: good catch, but as I was working on a fix, it occurred to me that the behavior is in fact correct the way it is currently.  

Maybe we should only update the docs to mention that `mode: age` will generate more accurate values (because it already uses the `refDate`) or change the default mode to age

Comment (ST-DDT) [reply src/modules/date/index.ts]: One way to ensure the age is 18+ is by subtracting 19 instead of 18 for the year mode.

Comment (ST-DDT) [reply src/modules/date/index.ts]: > change the default mode to age

That would be a breaking change. (We could do that, but not in a simple fix for v8.x)

Comment (mumumilk) [reply src/modules/date/index.ts]: >One way to ensure the age is 18+ is by subtracting 19 instead of 18 for the year mode.

much simpler than the way I was heading to, thanks

**Review by ST-DDT — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]
