### PR TITLE
fix(image): dataUri should return random type

### LINKED ISSUE #3346: faker.image.dataUri() always returns svg-base64
faker.image.dataUri() should return either of the 'svg-uri', 'svg-base64' types if no type if provided, but actually always returns 'svg-base64'

```
> faker.image.dataUri()
'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgYmFzZVByb2ZpbGU9ImZ1bGwiIHdpZHRoPSIzNjI2IiBoZWlnaHQ9IjM3NDUiPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IiM4ZTk3ZTgiLz48dGV4dCB4PSIxODEzIiB5PSIxODcyLjUiIGZvbnQtc2l6ZT0iMjAiIGFsaWdubWVudC1iYXNlbGluZT0ibWlkZGxlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSI+MzYyNngzNzQ1PC90ZXh0Pjwvc3ZnPg=='
> faker.image.dataUri()
'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgYmFzZVByb2ZpbGU9ImZ1bGwiIHdpZHRoPSIxOTI2IiBoZWlnaHQ9IjI2MjgiPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IiNhNTc3ZDMiLz48dGV4dCB4PSI5NjMiIHk9IjEzMTQiIGZvbnQtc2l6ZT0iMjAiIGFsaWdubWVudC1iYXNlbGluZT0ibWlkZGxlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSI+MTkyNngyNjI4PC90ZXh0Pjwvc3ZnPg=='
> faker.image.dataUri()
'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgYmFzZVByb2ZpbGU9ImZ1bGwiIHdpZHRoPSIyMzc4IiBoZWlnaHQ9IjExNDAiPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IiNlZGMzY2EiLz48dGV4dCB4PSIxMTg5IiB5PSI1NzAiIGZvbnQtc2l6ZT0iMjAiIGFsaWdubWVudC1iYXNlbGluZT0ibWlkZGxlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSI+MjM3OHgxMTQwPC90ZXh0Pjwvc3ZnPg=='
> faker.image.dataUri()
'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgYmFzZVByb2ZpbGU9ImZ1bGwiIHdpZHRoPSI2MjUiIGhlaWdodD0iMjA3NiI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iIzBhNzhhYiIvPjx0ZXh0IHg9IjMxMi41IiB5PSIxMDM4IiBmb250LXNpemU9IjIwIiBhbGlnbm1lbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0id2hpdGUiPjYyNXgyMDc2PC90ZXh0Pjwvc3ZnPg=='
> faker.image.dataUri()
'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgYmFzZVByb2ZpbGU9ImZ1bGwiIHdpZHRoPSIxMjMyIiBoZWlnaHQ9IjEzNDAiPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IiMzNmE2OGMiLz48dGV4dCB4PSI2MTYiIHk9IjY3MCIgZm9udC1zaXplPSIyMCIgYWxpZ25tZW50LWJhc2VsaW5lPSJtaWRkbGUiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IndoaXRlIj4xMjMyeDEzNDA8L3RleHQ+PC9zdmc+'
```

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #3346

arrayElements() was used by mistake instead of arrayElement()

### CODE REVIEW

File: src/modules/image/index.ts [hunk 1]
```diff
@@ -378,7 +378,7 @@ export class ImageModule extends ModuleBase {
       width = this.faker.number.int({ min: 1, max: 3999 }),
       height = this.faker.number.int({ min: 1, max: 3999 }),
       color = this.faker.color.rgb(),
-      type = this.faker.helpers.arrayElements(['svg-uri', 'svg-base64']),
+      type = this.faker.helpers.arrayElement(['svg-uri', 'svg-base64']),
```
Comment (ST-DDT) [inline src/modules/image/index.ts:381]: Please also fix the default value in the jsdocs.

**Review by ST-DDT — APPROVED** [review]
I wonder why TS didn't warn here.
