### PR TITLE
fix(person): change fullName to use name patterns

### LINKED ISSUE #1211: Add the concept of order for `firstName` and `lastName` in `name.fullName`
### Clear and concise description of the problem

The sequence of Japanese names is lastName followed by firstName in the Japanese-speaking world.
ex: YAMADA TARO.
YAMADA is lastName.
TARO is firstName.
I would like to incorporate this into faker as well.

// This sentence relies on machine translation.

### Suggested solution

Add full_name_order to NameDefinitions.
The full_name_order is as follows.
```typescript
export type FullNameOrder = 'normal' | 'reverse';
```

Add the ordering process using this to fullName in src/modules/name/index.ts.
```typescript
    if (this.faker.definitions.name.full_name_order === 'reverse') {
      nameParts.push(lastName);
      nameParts.push(firstName);
    } else {
      nameParts.push(firstName);
      nameParts.push(lastName);
    }
```

### Alternative

I do not understand Faker or programming that deeply, so the best approach may be something else.

### Additional context

In addition to this, we would like to add a collection of first names for Japanese men and a collection of first names for Japanese women.

### PR DESCRIPTION
**Pull request by matthewmayer**
Fixes #1211

This is work-in-progress tentative draft fix for #1211 which is a simplified version of the ideas in #1216.

- Allows the use of the src/locales/*/person/name.ts legacy patterns
- Allows for locales where first name and last name are reversed e.g. ja, zh_CN
- Allows for prefixes and suffixes in some languages
- Removes gender-specific templates. In particular you don't need to repeat male and female patterns in name.ts any more so I simplified all locales where that was the case
- Since src/locales/en/person/name.ts is defined, don't need a final fallback, we can assume there will always be a name pattern
- Uses the new weightedArrayElement to replicate the old behavior of fullName where prefixes and suffixes are only addded to a small proportion of names https://github.com/faker-js/faker/pull/1654

## Sample output: en, generic

```
'Ramiro Wehner',      'Ernest Smith',
  'Kristopher Gutmann', 'Jason Price',
  'Shannon Kuhn',       'Camille Schoen',
  'Israel Kreiger',     'Mrs. Diane Spinka MD',
  'Jon Shields',        'Luke Boyer',
  'Gerard Parker',      'Mrs. Amber DuBuque IV',
  'Ms. Flora Keebler',  'Orlando Cummerata',
  'Ross Friesen MD',    'Miss Sonya Kuhlman V',
  'Estelle DuBuque',    'Malcolm Weber PhD',
  'Mr. Juan Hamill',    'Ms. Lora Rempel MD'
```
## Sample output: en, male

```
'Morris Cummerata I',
  'Jesse Wolff',
  'Harry Erdman',
  'Rudy Swift',
  'Dwight Feest',
  'Nathan Schumm',
  'Roosevelt Kuhn MD',
  'Shawn Stokes I',
  'Mr. Dexter Wintheiser IV',
  'Leonard Marks Jr.',
  'Lloyd Von',
  'Jon Frami',
  'Mr. Jody Sipes MD',
  'Micheal Ward',
  'Alberto Feest',
  'Terrance Schuppe',
  'Leroy Feest IV',
  'Mr. Duane Senger I',
  'Ismael Walsh',
  'Claude Casper'
```

## Sample output: en, female

```
 'Patty West',            'Hope Lueilwitz',
  'Gwen Skiles',           'Anita Homenick',
  "Lucia O'Reilly DVM",    'Dr. Ashley Aufderhar',
  'Karla Keeling',         'Sonia Corwin',
  'Kathryn Lang',          'Velma Mertz',
  'Raquel Funk II',        'Amanda Ebert',
  'Mrs. Claire Corwin II', 'Penny Reichel',
  'Ms. Rachael Hermann V', 'Adrienne Roob',
  'Alice Fisher',          'Patty Stehr',
  'Sally Lesch',           'Dianna Kohler'
```

## Sample output: es

```
'Mrs. Jennifer Alanis Pineda',
  'Miss Ana Saavedra Muñiz',
  'Ms. Marta Moya Valencia',
  'Dr. María de los Ángeles Ledesma Osorio',
  'Ángel Solís Orta',
  'Lorena Munguía Rivera',
  'Laura Meza Moya',
  'Laura Alonso Orozco',
  'Mr. Pablo Mora Pichardo',
  'Daniel Pizarro Rosado',
  'Ana Salcedo de Jesús',
  'Mr. Manuel Rascón Leyva',
  'Iván Delarosa Bustos',
  'Mrs. Andrea Rael Navarro',
  'Dr. Jennifer Arce Garrido',
  'Dr. Daniel Rael Arce',
  'Mrs. Jennifer Marrero Caraballo',
  'Sergi Carrero Valladares',
  'Dr. Pablo Jaimes Espinoza',
  'Rubén Chávez Lira'
```

## Sample output: zh_CN (note lastname before firstname)

```
'郭语汐', '邵宇轩', '韩丹',
  '洪国栋', '阎俊熙', '曾国良',
  '梁丽萍', '秦浩然', '胡萍',
  '任国英', '熊雨桐', '郭梓涵',
  '崔婷',   '莫兰英', '程依诺',
  '罗国香', '陶国英', '卢辉',
  '邓志明', '夏洁'
```

## All locales
(note there are still first name issues in some languages due to https://github.com/faker-js/faker/pull/1610#issuecomment-1328279140 )
```js
Object.keys(faker.locales).forEach((locale) => {
  faker.setLocale(locale);
  console.log(
    `${locale}: (${
      faker.locales[locale].person?.name?.length || 0
    }) ${faker.person.fullName()},${faker.person.fullName({
      sex: 'male',
    })},${faker.person.fullName({ sex: 'female' })}`
  );
});
```

Number of name patterns is shown in paretheses
```
af_ZA: (0) Eugene van Staden,Mr. Bobbie Krige,Elsa Swart
ar: (3) Mr. عمار سويس,Mr. ريان فقوسة,جاوحدو خلود
az: (3) Vəsiyeva Elyanora,Quliyev Nadir,Laura
cz: (3) Jaroslav Jirků,Mr. Augustýn Jeřábek,Dr. Léda Husáková
de: (2) Martha Tidow,Hendrik Lack,Ms. Daria Müller
de_AT: (3) Mr. Ted Klimczak,Howard Einert,Lee Nytra
de_CH: (1) Loretta Bühlmann,Caleb Zimmermann,Alexis Schärer
dv: (1) ޖުވައިރިއްޔާ ދަލޫފް,އިބްރާހީމް ހައްފާފް,ޢާތިކާ ޣިނާ
el: (3) Dr. Bobbie Αναγνωστάκης,Mr. Bobby Μακρής,Dr. Eloise Πανταζής
en: (10) Casey Reynolds IV,Dr. Lester Parisian,Mrs. Marie Kassulke
en_AU: (0) Mr. Cedric Hudson Sr.,Sam Ernser,Dr. Shawna Hudson MD
en_AU_ocker: (0) Alfred Robinson II,Ralph Robinson,Ginger LeQuesne
en_BORK: (0) Jeannette Bosco,Jody Hilll,Ms. Carole Jakubowski
en_CA: (0) Lois Bergnaum,Darryl Rau,Catherine Mohr
en_GB: (0) Julio Rippin,Terrence Swift,Lauren Ledner
en_GH: (2) Baaba Wiafe,Christian Otiwa,Esi Baawia
en_IE: (0) Valerie Dooley Sr.,Dr. Rafael Rice,Miss Tracey Rippin
en_IN: (0) Jonathan Kaul,Jon Asan,Shari Kaur
en_NG: (2) Emmanuel Lawal,Akanni Onose,Aderonke Aminat
en_US: (0) Pedro Dibbert,Travis Corkery,Martha Yost
en_ZA: (2) Parnell Colleen,Dave Dube,Debbie Grant
es: (2) Ángel Posada Armendáriz,Jorge Pedraza Velázquez,Roser Guzmán Ocampo
es_MX: (4) Derrick Urrutia Manzanares,Moses Acosta de Tórrez,Carol Adorno Khalid
fa: (2) میلاد لاجوردی,Mr. مجید قنبری,آنیتا مفتاح
fi: (1) Lauri Turunen,Tapio Aaltonen,Kaarina Kallio
fr: (3) Poirier Claude,Leclercq Zacharie,Abigaïl Arnaud
fr_BE: (3) Bob Andre I,Zinedine Fournier IV,Benedicte Klocko Fils
fr_CA: (0) Taylor Schiller,Nelson Hammes,Gwendolyn Little
fr_CH: (3) Eleanor Küng,Mr. Alessio Bossy,Luena Geisendorf
ge: (2) Mr. Mack დავითიშვილი,Cedric ტაბაღუა,Bertha სულაშვილი
he: (2) Ms. נוי איש שלום,מיכאל אשל,אפריל חנני
hr: (3) Biserka Maruna,Dr. Roko Džakić,Adriana Raspudić
hu: (2) Dr. Balog Olívia,Kozma Dávid,Vincze Izabella
hy: (3) Նարինե Թադևոսյան PhD,Մոնթե Բաբայան Sr.,Եվա Գալստյան II
id_ID: (3) Titin Putri,Niyaga Mulyono Suwarno,Kiandra Rahimah
it: (2) Barsaba Campus,Mr. Elia Zamboni,Mrs. Melania Loffredo
ja: (1) 清水 彩花,渡辺 義雄,清水 貞子
ko: (1) 단 Margaret,황 Spencer,도 Ruby
lv: (6) Lība Auziņa k-dze,Legzdiņš Andris,Līga Amālija Zviedre
mk: (2) Галена Гермова,д-р Србо Кондовски,г-ѓа Грозда Василеска
nb_NO: (5) Anders Rasmussen III,Joakim Jacobsen Martinsen,Miss Oda Kristiansen
ne: (0) Ms. Lydia Niroula,Jake Adhikari,Nadine Basnet
nl: (4) Ms. Demi Brink,Nouri Koning I,Bowie Broek III
nl_BE: (3) Mrs. Stacy Vandamme,Theodore Declerck,Betsy Willems
pl: (2) Mrs. Klementyna Lipski,Dr. Atanazy Kwiecień,Mrs. Aida Dziuba
pt_BR: (3) Isis Melo,Lucas Xavier Jr.,Dr. Ana Luiza Souza
pt_PT: (2) Sra. Vânia Mota,Feliciano Albuquerque,Dra. Ana Tavares
ro: (3) Dr. Daniel Dascalu,Dr. Francisc Stoian,Safta Miu
ru: (4) Никон Артурович Борисов,Смирнов Аникей Исидорович,Алексеева Дарья
sk: (3) Klára Vicenová Phd.,Filip Kolár Phd.,Otília Pupáková
sv: (4) Lisa Abrahamsson Nordström,Kevin Nilsson Samuelsson,Camilla Ström Svensson
tr: (2) Dr. Peyami Başoğlu,Dr. Yahya Yetkiner,Mrs. Kamuran Orbay
uk: (4) Горова Добринка,Кулинич Сніжан Григорійович,Анна Арсеніївна Латанська
ur: (3) سیف شریف چہارم,Mr. احسن الحق,مشال اللَہ
vi: (1) Trường Liên Vương,Tường Anh Lâm,Hiếu Hạnh Tô
zh_CN: (1) 毛兰英,刘宇航,顾燕
zh_TW: (1) 賴Ramona,沈Jeffery,程Katie
zu_ZA: (0) Bhekizizwe Ndandali,Velaphi Zondi,Sindisiwe Moseley
```

### CODE REVIEW

File: src/modules/person/index.ts [hunk 1]
```diff
@@ -165,33 +165,22 @@ export class PersonModule {
...
+    );
 
-    const suffix = this.faker.helpers.maybe(() => this.suffix(), {
-      probability: 0.125,
+    const fullName = this.faker.helpers.mustache(fullNamePattern, {
+      'person.gender': () => this.gender(),
+      'person.prefix': () => this.prefix(sex),
+      'person.first_name': () => options.firstName || this.firstName(sex),
+      'person.middle_name': () => this.middleName(sex),
+      'person.last_name': () => options.lastName || this.lastName(sex),
```
Comment (ST-DDT) [inline src/modules/person/index.ts]: I prefer using the method notation here e.g. `'person.firstName'` since this effectively does exactly that.

File: src/locales/en/person/name.ts [hunk 2]
```diff
@@ -1,7 +1,6 @@
 export default [
-  '{{person.prefix}} {{person.first_name}} {{person.last_name}}',
-  '{{person.first_name}} {{person.last_name}} {{person.suffix}}',
-  '{{person.first_name}} {{person.last_name}}',
-  '{{person.male_first_name}} {{person.last_name}}',
-  '{{person.female_first_name}} {{person.last_name}}',
+  ...Array(7).fill('{{person.first_name}} {{person.last_name}}'), //70% of the time we want a first and last name
```
Comment (matthewmayer) [inline src/locales/en/person/name.ts]: @ST-DDT any thoughts on a smarter way we could achieve this without duplicates in the array?

Comment (ST-DDT) [reply src/locales/en/person/name.ts]: Introduce a new helper method: `weightedArrayElement`
We already considered it before, but didn't have time for that yet.

**Comment by matthewmayer** [comment]
I have added a new helper function `faker.helpers.weightedArrayElement` as suggested. 

I converted the existing name patterns to use weights (roughly, I tried to have prefixes/suffixes on 10-20% of the names only, people who know the locales better could tweak this later.)

**Comment by ST-DDT** [comment]
> I have added a new helper function `faker.helpers.weightedArrayElement` as suggested.

Could you please move that to a separate PR? This is getting harder and harder to review.

**Comment by matthewmayer** [comment]
I will change this back to draft for now and split into some smaller PRs

**Comment by matthewmayer** [comment]
Note i will redo a simplified version of this PR once #1654 and #1665 have been merged.

One thing i was thinking, person/name.ts is not the most descriptive name. Maybe this could be modified to `person/name_patterns.ts` or `person/full_name_patterns.ts` as part of this PR?

**Comment by ST-DDT** [comment]
> One thing i was thinking, person/name.ts is not the most descriptive name. Maybe this could be modified to `person/name_patterns.ts` or `person/full_name_patterns.ts` as part of this PR?

You are right. We also considered renaming other pattern files such as location street and city pattern files.

I'm not sure whether it should be done in a separate PR though (to split simple renames from functional changes and locale additions).

**Comment by matthewmayer** [comment]
sure, it can wait until a later PR.

**Comment by matthewmayer** [comment]
now that https://github.com/faker-js/faker/pull/1654 has landed i have updated this PR to use the new method.

File: src/locales/en/person/name.ts [hunk 3]
```diff
@@ -1,7 +1,16 @@
 export default [
-  '{{person.prefix}} {{person.first_name}} {{person.last_name}}',
-  '{{person.first_name}} {{person.last_name}} {{person.suffix}}',
-  '{{person.first_name}} {{person.last_name}}',
-  '{{person.male_first_name}} {{person.last_name}}',
-  '{{person.female_first_name}} {{person.last_name}}',
+  { value: '{{person.first_name}} {{person.last_name}}', weight: 49 },
```
Comment (matthewmayer) [inline src/locales/en/person/name.ts]: note these rather arbitrary numbers are to reproduce the current behavior of fullName in `en`:

1/8 of the time a prefix is added
1/8 of the time a suffix is added

Thus in every 64 names, 1 gets both, 7 get suffix, 7 get prefix, and 49 get neither

Comment (Shinigami92) [reply src/locales/en/person/name.ts]: Should we add this as an inline comment instead of here a comment on GitHub?

Comment (ST-DDT) [reply src/locales/en/person/name.ts]: I don't see a need for it.

File: src/modules/person/index.ts (hunk 1 above)
Comment (ST-DDT) [reply src/modules/person/index.ts]: Please use the method notation here and in the locales: `'person.firstName'` (for all patterns that get replaced via `mustache`)

**Review by ST-DDT — CHANGES_REQUESTED** [review]

File: src/modules/person/index.ts (hunk 1 above)
Comment (matthewmayer) [reply src/modules/person/index.ts]: Do we actually need the 'person.' part? Could simplify it by leaving it off.

Comment (ST-DDT) [reply src/modules/person/index.ts]: "Need": No, but then we couldn't push it through `faker.helpers.fake` anymore (and we don't have to).
But it makes it a bit more consistent with other patterns.

**Comment by ST-DDT** [comment]
This also needs a rebase.

File: src/locales/de/person/name.ts [hunk 4]
```diff
@@ -1,7 +1,7 @@
...
-  '{{person.prefix}} {{person.first_name}} {{person.last_name}}',
-  '{{person.first_name}} {{person.nobility_title_prefix}} {{person.last_name}}',
-  '{{person.first_name}} {{person.last_name}}',
-  '{{person.male_first_name}} {{person.last_name}}',
-  '{{person.female_first_name}} {{person.last_name}}',
+  {
+    value: '{{person.prefix}} {{person.firstName}} {{person.lastName}}',
+    weight: 1,
+  },
+  { value: '{{person.firstName}} {{person.lastName}}', weight: 9 },
```
Comment (ST-DDT) [inline src/locales/de/person/name.ts:6]: What happened with the `nobility_title_prefix` one?

Comment (matthewmayer) [reply src/locales/de/person/name.ts:6]: i changed it to use middleName as it was only in one locale.

File: src/modules/person/index.ts (hunk 1 above)
Comment (matthewmayer) [reply src/modules/person/index.ts]: done

File: src/locales/de/person/name.ts (hunk 4 above)
Comment (ST-DDT) [reply src/locales/de/person/name.ts:6]: But this locale doesn't have the middle name one, but has the `nobility_title_prefix` file.

Comment (matthewmayer) [reply src/locales/de/person/name.ts:6]: oops that was an oversight. Changed de to work like de_AT

**Review by ST-DDT — DISMISSED** [review]

**Review by ST-DDT — DISMISSED** [review]

File: src/definitions/person.ts [hunk 5]
```diff
@@ -26,9 +26,9 @@ export type PersonDefinitions = LocaleEntry<{
   suffix: string[];
 
   /**
-   * A list of patterns used to generate names.
+   * A weighted list of patterns used to generate names.
    */
-  name: string[];
+  name: { value: string; weight: number }[];
```
Comment (Shinigami92) [inline src/definitions/person.ts]: I prefer 
```suggestion
  name: Array<{ value: string; weight: number }>;
```

But we can also turn on an eslint rule for that

**Comment by ST-DDT** [comment]
FFR: nl_tussenvoegsel is not gender specific according to https://discord.com/channels/929487054990110771/1067095374533251164/1067117512841502822.

File: src/locales/de/person/female_middle_name.ts [hunk 6]
```diff
@@ -0,0 +1,2 @@
+// This is a nobility title prefix, but for simplicity it acts like a middle name
+export default ['zu', 'von', 'vom', 'von der'];
```
Comment (xDivisionByZerox) [inline src/locales/de/person/female_middle_name.ts]: I don't see how this is "for simplicity". This basically adds a "bug" to the `person.middleName()` function for the locale `de`. Furthermore, by removing the lcoale data, this PR has to be considered a breaking change (due to possible direct access and via `faker.helpers.fake()`).

File: src/modules/person/index.ts [hunk 7]
```diff
@@ -166,33 +166,22 @@ export class PersonModule {
...
-
-    const nameParts: string[] = [];
-    const prefix = this.faker.helpers.maybe(() => this.prefix(sex), {
-      probability: 0.125,
-    });
-
-    if (prefix) {
-      nameParts.push(prefix);
-    }
+    const sex =
```
Comment (xDivisionByZerox) [inline src/modules/person/index.ts]: We actually have a rule (sadly not documented so far) to first normalize the `options` to an object (if required) and destruct it afterward and default options while doing so. This makes it easy to see what actually happens with all option parameters.

Could you do that as well here?

File: src/locales/de/person/female_middle_name.ts (hunk 6 above)
Comment (matthewmayer) [reply src/locales/de/person/female_middle_name.ts]: i reverted the changes to nobility_title_prefix and tusssenvoegsel in de, de_AT and nl. This is probably best addressed instead via the strategy used in #1777 ie move the affixes into the surnames file. But i dont know enough about German to do that personally so can probably be addressed in a seperate follow up PR like #1777

File: src/modules/person/index.ts (hunk 7 above)
Comment (matthewmayer) [reply src/modules/person/index.ts]: dont totally follow, do you have an example from elsewhere in the code

Comment (xDivisionByZerox) [reply src/modules/person/index.ts]: Yes, of course, No Problem. Sadly there is no example in the `PersonModule` since its arguments are yet to be standardized according to #1349.

Have a look at the `NumberModule` for example:
Function Signature:
https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L41-L58

Handling for the non-object argument (first thing that is done in  the function):
https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L59-L61

Destruction and default assignments (directly followed after the argument normalization):
 https://github.com/faker-js/faker/blob/86ae8b9d698f5b2c75214b0cfef869122a591001/src/modules/number/index.ts#L63

Comment (xDivisionByZerox) [reply src/modules/person/index.ts]: In the fullName case, this would look like this:
```ts
fullName(options: {...}): string {
  const {
    sex = this.faker.helpers.arrayElement([Sex.Female, Sex.Male]),
    firstName = this.firstName(sex),
    lastName = this.lastName(sex),
  } = options;

  // further implementation
}
```

**Review by ST-DDT — DISMISSED** [review]

**Review by xDivisionByZerox — DISMISSED** [review]

**Comment by ST-DDT** [comment]
Could you please fix the new lint error?

**Review by ST-DDT — APPROVED** [review]

**Review by xDivisionByZerox — APPROVED** [review]

**Review by Shinigami92 — APPROVED** [review]

**Comment by matthewmayer** [comment]
Yay! Thanks for all the help with this
