### PR TITLE
fix(internet): ensure domainWord always returns a valid value in all locales

### LINKED ISSUE #3251: Korean faker giving invalid urls
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

When using `fakerKO` and calling `internet.url()` you get urls that look like `https://--.com`

### Minimal reproduction code

https://stackblitz.com/edit/faker-js-demo-i7vsqq?file=index.ts

### Additional Context

_No response_

### Environment Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @faker-js/faker: ^9.2.0 => 9.2.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

### PR DESCRIPTION
**Pull request by matthewmayer**
fix #3251

If `faker.word.noun()/adjective()` doesnt return useful output, fall back to `faker.lorem.word()` or a random string

Fixes issues in `fa,ko,zh-CN`

```
af_ZA silent-couch
ar married-minister
az trained-thigh
base
cs_CZ thick-strategy
da larmende-myndighed
de ehrgeizig-verhutung
de_AT heimlich-kilometer
de_CH standhaft-ph-wert
dv tangible-reach
el small-trench
en tough-perfection
en_AU baggy-alert
en_AU_ocker rare-platypus
en_BORK dim-euphonium
en_CA authentic-viability
en_GB flowery-larva
en_GH ecstatic-characterization
en_HK cumbersome-desk
en_IE self-reliant-academics
en_IN deficient-doorpost
en_NG troubled-co-producer
en_US happy-taro
en_ZA tense-chasuble
eo insistent-sprinkles
es esteemed-catalyst
es_MX crushing-bookend
fa omhjh-vkzoy
fi feline-independence
fr sympathique-communaute-etudiante
fr_BE lache-hote
fr_CA rectangulaire-personnel
fr_CH timide-rectorat
fr_LU turquoise-commissionnaire
fr_SN dense-police
he stark-entry
hr golden-priesthood
hu narancssargas-szalagos-likacsosgomba
hy short-transom
id_ID tall-elevation
it grimy-pomelo
ja whopping-slime
ka_GE frightened-sarong
ko slek-adwpi
lv unhealthy-dream
mk natural-heroine
nb_NO apenbar-eyebrow
ne necessary-mixture
nl circular-space
nl_BE unknown-range
pl talkative-hyphenation
pt_BR bright-membership
pt_PT chilly-devil
ro bright-spirit
ro_MD flashy-obesity
ru parallel-feather
sk soft-fedora
sr_RS_latin unfinished-bog
sv vengeful-flight
th brilliant-cassava
tr foolish-widow
uk strong-expense
ur warm-distinction
uz_UZ_latin petty-label
vi delectable-kick
yo_NG both-pigsty
zh_CN venustas-reporter
zh_TW better-range
zu_ZA inexperienced-republican
```

### CODE REVIEW

File: src/modules/internet/index.ts [hunk 1]
```diff
@@ -595,9 +595,32 @@ export class InternetModule extends ModuleBase {
...
+
+      const slug2 = this.faker.helpers.slugify(this.faker.lorem.word());
+      if (isValidSlug(slug2)) {
+        return slug2;
+      }
+
+      return this.faker.string.alpha({
+        casing: 'lower',
+        length: this.faker.number.int({ min: 4, max: 8 }),
+      });
```
Comment (ST-DDT) [inline src/modules/internet/index.ts:618]: I wonder whether we should modify the slugify method to do this by default/with option. 🤔 
Because this technically only produces valid output for domainWord, but slugify is still broken in those languages.

**Review by ST-DDT — APPROVED** [review]

File: src/modules/internet/index.ts (hunk 1 above)
Comment (matthewmayer) [reply src/modules/internet/index.ts:618]: I feel that would be surprising behaviour for a helper method. 

I think when we have a format with certain extra requirements like email addresses or domain names it's fine to do some extra "massaging" to get the output format we need.

**Review by xDivisionByZerox — APPROVED** [review]

**Review by ejcheng — APPROVED** [review]
