### PR TITLE
fix: address.nearbyGPSCoordinate

### LINKED ISSUE #321: Investigate why test address gps coords for non-metric sometimes fails
### Describe the bug

[`218ae3a` (#285)](https://github.com/faker-js/faker/pull/285/commits/218ae3ace1085244a83ac32f56cea93f123cf389)

### Reproduction

comment in the outcommented code and see that it sometimes fails

### Additional Info

Not sure if the test is written wrongly or if the function really is broken

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #321

### CODE REVIEW

**Comment by ST-DDT** [comment]
It looks like the float values caused massive issues especially since we stacked the calls on those values.
With the simplified implementation we have far less error and use a much larger part of the circle.

**Actual**
Min: 0.00042
Avg: 0.07065
Max: 0.14406

**Expected**
Min: 0.00000
Avg: 0.07500
Max: 0.15000

That's 96% coverage vs the old ~0.08%

@Shinigami92 Anything you want to change/fix here?

File: src/address.ts [hunk 1]
```diff
@@ -1,73 +1,9 @@
...
-  // Keep longitude in range [-180, 180]
-  if (lon2 > degreesToRadians(180)) {
-    lon2 = lon2 - degreesToRadians(360);
-  } else if (lon2 < degreesToRadians(-180)) {
-    lon2 = lon2 + degreesToRadians(360);
-  }
-
-  return [radiansToDegrees(lat2), radiansToDegrees(lon2)];
-}
+const kmPerDegree = 40_000 / 360; // in km/°
```
Comment (Shinigami92) [inline src/address.ts:6]: Script constants should be written in CONSTANT_CASE

But this should also be named with earth, cause maybe we later want to have some other circumferences for other custom planetoids

File: test/address.spec.ts [hunk 2]
```diff
@@ -1,6 +1,36 @@
...
+}
+
+function haversine(
+  latitude1: number,
+  longitude1: number,
+  latitude2: number,
+  longitude2: number,
+  isMetric: boolean
+) {
+  const EQUATORIAL_EARTH_RADIUS = 6378.137;
```
Comment (Shinigami92) [inline test/address.spec.ts:19]: We should move this out of the function

File: test/address.spec.ts [hunk 3]
```diff
@@ -89,12 +119,12 @@ const seededRuns = [
...
       cardinalDirectionAbbr: 'W',
       timeZone: 'Asia/Magadan',
-      nearbyGpsCoordinates: ['0.0503', '-0.0242'],
+      nearbyGpsCoordinates: ['-0.0287', '0.0596'],
     },
   },
 ];
 
-const NON_SEEDED_BASED_RUN = 5;
+const NON_SEEDED_BASED_RUN = 1;
```
Comment (Shinigami92) [inline test/address.spec.ts:127]:
```suggestion
const NON_SEEDED_BASED_RUN = 5;
```

File: test/address.spec.ts [hunk 4]
```diff
@@ -556,39 +586,14 @@ describe('address', () => {
...
-          let latFloat1: number;
-          let lonFloat1: number;
-          let isMetric: boolean;
-
-          for (let i = 0; i < 10000; i++) {
-            latFloat1 = parseFloat(faker.address.latitude());
-            lonFloat1 = parseFloat(faker.address.longitude());
-            const radius = Math.random() * 99 + 1; // range of [1, 100)
-            isMetric = Math.round(Math.random()) === 1;
+          for (let i = 0; i < 100; i++) {
```
Comment (Shinigami92) [inline test/address.spec.ts:589]: At least thousends, maybe even back to 10_000?

```suggestion
          for (let i = 0; i < 1_000; i++) {
```

```suggestion
          for (let i = 0; i < 10_000; i++) {
```

File: test/address.spec.ts [hunk 5]
```diff
@@ -1,6 +1,36 @@
...
+  latitude1: number,
+  longitude1: number,
+  latitude2: number,
+  longitude2: number,
+  isMetric: boolean
+) {
+  const EQUATORIAL_EARTH_RADIUS = 6378.137;
+  const distanceLatitude = degreesToRadians(latitude2 - latitude1);
+  const distanceLongitude = degreesToRadians(longitude2 - longitude1);
+  const a =
```
Comment (Shinigami92) [inline test/address.spec.ts:22]: Could we find a better name for `a`? I currently don't know what it is :thinking:

File: test/address.spec.ts [hunk 6]
```diff
@@ -556,39 +586,14 @@ describe('address', () => {
...
-          for (let i = 0; i < 10000; i++) {
-            latFloat1 = parseFloat(faker.address.latitude());
-            lonFloat1 = parseFloat(faker.address.longitude());
-            const radius = Math.random() * 99 + 1; // range of [1, 100)
-            isMetric = Math.round(Math.random()) === 1;
+          for (let i = 0; i < 100; i++) {
+            const latitude1 = +faker.address.latitude();
+            const longitude1 = +faker.address.longitude();
+            const radius = faker.datatype.float({ min: 1, max: 100 });
+            const isMetric = faker.datatype.boolean();
```
Comment (Shinigami92) [inline test/address.spec.ts:593]: I would like to move this out to the `it` as `it.each` and then split the runs into half for each, so maybe 5_000/5_000?

**Review by ST-DDT — DISMISSED** [review]

File: test/address.spec.ts [hunk 7]
```diff
@@ -556,39 +586,14 @@ describe('address', () => {
...
-
-          for (let i = 0; i < 10000; i++) {
-            latFloat1 = parseFloat(faker.address.latitude());
-            lonFloat1 = parseFloat(faker.address.longitude());
-            const radius = Math.random() * 99 + 1; // range of [1, 100)
-            isMetric = Math.round(Math.random()) === 1;
+          for (let i = 0; i < 100; i++) {
+            const latitude1 = +faker.address.latitude();
+            const longitude1 = +faker.address.longitude();
+            const radius = faker.datatype.float({ min: 1, max: 100 });
```
Comment (Shinigami92) [inline test/address.spec.ts:592]: We could control this one also a bit more with it.each together with the `isMetric`

so what about e.g. `it.each(times(100).map(i=>[i+1,isMetric,radius]))` ...

Okay maybe a 3-stacked for-loop is better here?
```ts
for (const isMetric of [true, false])
  for (const radius of times(100))
    for (const run of times(1000))
      it(...)
```

File: test/address.spec.ts (hunk 4 above)
Comment (ST-DDT) [reply test/address.spec.ts:589]: I wouldn't recommend that, as this just wastes time. We don't do the NON_SEEDED_BASE_RUN that often either.

File: test/address.spec.ts (hunk 5 above)
Comment (ST-DDT) [reply test/address.spec.ts:25]: Me neither. Maybe check the internet?

File: test/address.spec.ts [hunk 8]
```diff
@@ -555,119 +588,45 @@ describe('address', () => {
...
-                Math.sin(dLon / 2);
-            const distance = R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
-
-            return isMetric ? distance : kilometersToMiles(distance);
+        for (const isMetric of [true, false]) {
+          for (const radius of times(100)) {
+            it(`should return random gps coordinate within a distance of another one (${JSON.stringify(
+              { isMetric, radius }
+            )})`, () => {
+              for (let i = 0; i < 100; i++) {
```
Comment (ST-DDT) [inline test/address.spec.ts:596]: A single run is probably enough.
Otherwise we end up with too many checks:
- `runs * isMetric * radius * i`
- `5 * 2 * 100 * 100`
- `= 100000`

If you omit the i-for-loop, then we still have `1000` test runs.
Maybe leave the loop there, but just reduce it to `5`,
that way it's very easy to increment the runs if there is a need to debug it.

**Review by ST-DDT — CHANGES_REQUESTED** [review]

File: src/address.ts [hunk 9]
```diff
@@ -452,6 +447,12 @@ export class Address {
         precision: 0.001,
       }) * errorCorrection; // in km
 
+    /**
+     * The distance in km per degree for earth.
+     */
+    // TODO @Shinigami92 2022-04-26: Provide an option property to provide custom circumferences.
```
[the remark this answers is not in the document]
Comment (Shinigami92) [reply src/address.ts:453]: Done https://github.com/faker-js/faker/issues/878

File: test/address.spec.ts (hunk 5 above)
Comment (Shinigami92) [reply test/address.spec.ts:25]: I found this https://www.movable-type.co.uk/scripts/latlong.html
But even there it is called `a`. :shrug: 
Because I don't want to stop this PR to get merged just based on that, lets move on :shrug:

**Review by ST-DDT — APPROVED** [review]

**Review by import-brain — APPROVED** [review]
